bucket: spring-bucket-jiabeiyuan
path_to_json_key: ./credentials.json

server:
  port: 8080

logging:
#  config: logback.xml
  level:
    org.springframework: INFO
    com.test: INFO

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB